name = "timers"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-14"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"